In [1]:
import tensorflow as tf
import time
import multiprocessing
import numpy as np

In [2]:
class MyTest():
    def __init__(self, thread_pool_size=4):
        self.a=[np.ones((2,2), dtype=np.float32) * i for i in range(1000)]
        self.pool = multiprocessing.pool.ThreadPool(thread_pool_size)
    def __len__(self):
        return len(self.a)
    def __getitem__(self, i):
        #print("loading ", i)
        time.sleep(0.02)
        return self.a[i]
    def getitems(self, indices):
        return np.array(self.pool.map(self.__getitem__ ,indices))


In [7]:
%%timeit
t=MyTest(10)
print(t.getitems(list(range(100))))

[[[ 0.  0.]
  [ 0.  0.]]

 [[ 1.  1.]
  [ 1.  1.]]

 [[ 2.  2.]
  [ 2.  2.]]

 [[ 3.  3.]
  [ 3.  3.]]

 [[ 4.  4.]
  [ 4.  4.]]

 [[ 5.  5.]
  [ 5.  5.]]

 [[ 6.  6.]
  [ 6.  6.]]

 [[ 7.  7.]
  [ 7.  7.]]

 [[ 8.  8.]
  [ 8.  8.]]

 [[ 9.  9.]
  [ 9.  9.]]

 [[10. 10.]
  [10. 10.]]

 [[11. 11.]
  [11. 11.]]

 [[12. 12.]
  [12. 12.]]

 [[13. 13.]
  [13. 13.]]

 [[14. 14.]
  [14. 14.]]

 [[15. 15.]
  [15. 15.]]

 [[16. 16.]
  [16. 16.]]

 [[17. 17.]
  [17. 17.]]

 [[18. 18.]
  [18. 18.]]

 [[19. 19.]
  [19. 19.]]

 [[20. 20.]
  [20. 20.]]

 [[21. 21.]
  [21. 21.]]

 [[22. 22.]
  [22. 22.]]

 [[23. 23.]
  [23. 23.]]

 [[24. 24.]
  [24. 24.]]

 [[25. 25.]
  [25. 25.]]

 [[26. 26.]
  [26. 26.]]

 [[27. 27.]
  [27. 27.]]

 [[28. 28.]
  [28. 28.]]

 [[29. 29.]
  [29. 29.]]

 [[30. 30.]
  [30. 30.]]

 [[31. 31.]
  [31. 31.]]

 [[32. 32.]
  [32. 32.]]

 [[33. 33.]
  [33. 33.]]

 [[34. 34.]
  [34. 34.]]

 [[35. 35.]
  [35. 35.]]

 [[36. 36.]
  [36. 36.]]

 [[37. 37.]
  [37. 37.]]

 [[38. 38.]


[[[ 0.  0.]
  [ 0.  0.]]

 [[ 1.  1.]
  [ 1.  1.]]

 [[ 2.  2.]
  [ 2.  2.]]

 [[ 3.  3.]
  [ 3.  3.]]

 [[ 4.  4.]
  [ 4.  4.]]

 [[ 5.  5.]
  [ 5.  5.]]

 [[ 6.  6.]
  [ 6.  6.]]

 [[ 7.  7.]
  [ 7.  7.]]

 [[ 8.  8.]
  [ 8.  8.]]

 [[ 9.  9.]
  [ 9.  9.]]

 [[10. 10.]
  [10. 10.]]

 [[11. 11.]
  [11. 11.]]

 [[12. 12.]
  [12. 12.]]

 [[13. 13.]
  [13. 13.]]

 [[14. 14.]
  [14. 14.]]

 [[15. 15.]
  [15. 15.]]

 [[16. 16.]
  [16. 16.]]

 [[17. 17.]
  [17. 17.]]

 [[18. 18.]
  [18. 18.]]

 [[19. 19.]
  [19. 19.]]

 [[20. 20.]
  [20. 20.]]

 [[21. 21.]
  [21. 21.]]

 [[22. 22.]
  [22. 22.]]

 [[23. 23.]
  [23. 23.]]

 [[24. 24.]
  [24. 24.]]

 [[25. 25.]
  [25. 25.]]

 [[26. 26.]
  [26. 26.]]

 [[27. 27.]
  [27. 27.]]

 [[28. 28.]
  [28. 28.]]

 [[29. 29.]
  [29. 29.]]

 [[30. 30.]
  [30. 30.]]

 [[31. 31.]
  [31. 31.]]

 [[32. 32.]
  [32. 32.]]

 [[33. 33.]
  [33. 33.]]

 [[34. 34.]
  [34. 34.]]

 [[35. 35.]
  [35. 35.]]

 [[36. 36.]
  [36. 36.]]

 [[37. 37.]
  [37. 37.]]

 [[38. 38.]


In [9]:
t=MyTest(10)
tf_fun=lambda i: tf.numpy_function(t.__getitem__, [i] , tf.float32 )

In [10]:
%%timeit
ds=tf.data.Dataset.range(100).map(tf_fun)
for x in ds:
    pass

2.14 s ± 11.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
tf_fun2=lambda i: tf.numpy_function(t.getitems, [i] , tf.float32 )

In [14]:
%%timeit
ds=tf.data.Dataset.range(100).batch(10).map(tf_fun2).unbatch().batch(4)
for x in ds:
    print(x)
    # pass

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]]

 [[2. 2.]
  [2. 2.]]

 [[3. 3.]
  [3. 3.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[4. 4.]
  [4. 4.]]

 [[5. 5.]
  [5. 5.]]

 [[6. 6.]
  [6. 6.]]

 [[7. 7.]
  [7. 7.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[ 8.  8.]
  [ 8.  8.]]

 [[ 9.  9.]
  [ 9.  9.]]

 [[10. 10.]
  [10. 10.]]

 [[11. 11.]
  [11. 11.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[12. 12.]
  [12. 12.]]

 [[13. 13.]
  [13. 13.]]

 [[14. 14.]
  [14. 14.]]

 [[15. 15.]
  [15. 15.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[16. 16.]
  [16. 16.]]

 [[17. 17.]
  [17. 17.]]

 [[18. 18.]
  [18. 18.]]

 [[19. 19.]
  [19. 19.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[20. 20.]
  [20. 20.]]

 [[21. 21.]
  [21. 21.]]

 [[22. 22.]
  [22. 22.]]

 [[23. 23.]
  [23. 23.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[24. 24.]
  [24. 24.]]

 [[25. 25.]
  [25. 25.]]

 [[26. 26.]
  [26. 26.]]

 [[27. 27.]
  [27. 27.]]], shape=(4, 2, 2), dtype=float

tf.Tensor(
[[[48. 48.]
  [48. 48.]]

 [[49. 49.]
  [49. 49.]]

 [[50. 50.]
  [50. 50.]]

 [[51. 51.]
  [51. 51.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[52. 52.]
  [52. 52.]]

 [[53. 53.]
  [53. 53.]]

 [[54. 54.]
  [54. 54.]]

 [[55. 55.]
  [55. 55.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[56. 56.]
  [56. 56.]]

 [[57. 57.]
  [57. 57.]]

 [[58. 58.]
  [58. 58.]]

 [[59. 59.]
  [59. 59.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[60. 60.]
  [60. 60.]]

 [[61. 61.]
  [61. 61.]]

 [[62. 62.]
  [62. 62.]]

 [[63. 63.]
  [63. 63.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[64. 64.]
  [64. 64.]]

 [[65. 65.]
  [65. 65.]]

 [[66. 66.]
  [66. 66.]]

 [[67. 67.]
  [67. 67.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[68. 68.]
  [68. 68.]]

 [[69. 69.]
  [69. 69.]]

 [[70. 70.]
  [70. 70.]]

 [[71. 71.]
  [71. 71.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[72. 72.]
  [72. 72.]]

 [[73. 73.]
  [73. 73.]]

 [[74. 74.]
  [74. 74.]]

 [[75. 75.]
  [75. 75.]

tf.Tensor(
[[[0. 0.]
  [0. 0.]]

 [[1. 1.]
  [1. 1.]]

 [[2. 2.]
  [2. 2.]]

 [[3. 3.]
  [3. 3.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[4. 4.]
  [4. 4.]]

 [[5. 5.]
  [5. 5.]]

 [[6. 6.]
  [6. 6.]]

 [[7. 7.]
  [7. 7.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[ 8.  8.]
  [ 8.  8.]]

 [[ 9.  9.]
  [ 9.  9.]]

 [[10. 10.]
  [10. 10.]]

 [[11. 11.]
  [11. 11.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[12. 12.]
  [12. 12.]]

 [[13. 13.]
  [13. 13.]]

 [[14. 14.]
  [14. 14.]]

 [[15. 15.]
  [15. 15.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[16. 16.]
  [16. 16.]]

 [[17. 17.]
  [17. 17.]]

 [[18. 18.]
  [18. 18.]]

 [[19. 19.]
  [19. 19.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[20. 20.]
  [20. 20.]]

 [[21. 21.]
  [21. 21.]]

 [[22. 22.]
  [22. 22.]]

 [[23. 23.]
  [23. 23.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[24. 24.]
  [24. 24.]]

 [[25. 25.]
  [25. 25.]]

 [[26. 26.]
  [26. 26.]]

 [[27. 27.]
  [27. 27.]]], shape=(4, 2, 2), dtype=float

tf.Tensor(
[[[48. 48.]
  [48. 48.]]

 [[49. 49.]
  [49. 49.]]

 [[50. 50.]
  [50. 50.]]

 [[51. 51.]
  [51. 51.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[52. 52.]
  [52. 52.]]

 [[53. 53.]
  [53. 53.]]

 [[54. 54.]
  [54. 54.]]

 [[55. 55.]
  [55. 55.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[56. 56.]
  [56. 56.]]

 [[57. 57.]
  [57. 57.]]

 [[58. 58.]
  [58. 58.]]

 [[59. 59.]
  [59. 59.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[60. 60.]
  [60. 60.]]

 [[61. 61.]
  [61. 61.]]

 [[62. 62.]
  [62. 62.]]

 [[63. 63.]
  [63. 63.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[64. 64.]
  [64. 64.]]

 [[65. 65.]
  [65. 65.]]

 [[66. 66.]
  [66. 66.]]

 [[67. 67.]
  [67. 67.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[68. 68.]
  [68. 68.]]

 [[69. 69.]
  [69. 69.]]

 [[70. 70.]
  [70. 70.]]

 [[71. 71.]
  [71. 71.]]], shape=(4, 2, 2), dtype=float32)
tf.Tensor(
[[[72. 72.]
  [72. 72.]]

 [[73. 73.]
  [73. 73.]]

 [[74. 74.]
  [74. 74.]]

 [[75. 75.]
  [75. 75.]